name: Test Homebrew Formula

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    
    - name: Tap local repository (Unix)
      if: runner.os != 'Windows'
      run: |
        # Create a temporary tap name and tap the local directory
        mkdir -p $(brew --repo)/Library/Taps/test
        ln -sf $PWD $(brew --repo)/Library/Taps/test/homebrew-kgrep
    
    - name: Tap local repository (Windows)
      if: runner.os == 'Windows'
      run: |
        # Create a temporary tap name and tap the local directory
        mkdir -p "$(brew --repo)/Library/Taps/test"
        New-Item -ItemType Junction -Path "$(brew --repo)/Library/Taps/test/homebrew-kgrep" -Target $PWD
      shell: pwsh
    
    - name: Test formula syntax
      run: brew audit --strict test/kgrep/kgrep
    
    - name: Test formula installation
      run: |
        # Test that the formula can be installed
        brew install test/kgrep/kgrep
    
    - name: Test kgrep functionality (Unix)
      if: runner.os != 'Windows'
      run: |
        # Verify kgrep binary exists and is executable
        which kgrep
        
        # Test basic kgrep commands
        kgrep version
        kgrep --help
        
        echo "All kgrep functionality tests passed"
    
    - name: Test kgrep functionality (Windows)
      if: runner.os == 'Windows'
      run: |
        # Verify kgrep binary exists and is executable
        where kgrep
        
        # Test basic kgrep commands
        kgrep version
        kgrep --help
        
        Write-Host "All kgrep functionality tests passed"
      shell: pwsh 