name: Test Homebrew Formula

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    
    - name: Install kubectl
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        else
          brew install kubectl
        fi
    
    - name: Test formula syntax
      run: brew audit --strict kgrep.rb
    
    - name: Test formula installation
      run: |
        # Test that the formula can be installed
        brew install --formula ./kgrep.rb
    
    - name: Test kgrep functionality
      run: |
        # Verify kgrep binary exists and is executable
        which kgrep
        
        # Test basic kgrep commands
        kgrep version
        kgrep --help
        
        # Test that kgrep shows proper error for missing kubectl context
        # (This will fail since we don't have a k8s cluster, but should show expected error)
        kgrep pods --help || true
        
        echo "All kgrep functionality tests passed" 